/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acp_shell_NDKUtils */

#ifndef _Included_com_acp_shell_NDKUtils
#define _Included_com_acp_shell_NDKUtils

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acp_shell_NDKUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_acp_shell_NDKUtils_getKeyFormC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
